#!/usr/bin/env bash

. .env.example
. ./scripts/functions.sh

if [ "$# -eq 2" ]; then
    case "$0 $1 $2" in
        "$0 make env")
            makeEnvFile
        ;;
        "$0 install saltstack")
            installSaltStack
        ;;
        *)
            echo "Error! Check arguments!"
        ;;
    esac
else
    exit 1
fi
